apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
  namespace: cassandra
spec:
  cassandra:
    serverVersion: "4.0.3"
    serverImage: k8ssandra/cass-management-api:4.0.3
    telemetry:
      prometheus:
        enabled: true
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: gp3
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
    config:
      jvmOptions:
        heapSize: 31Gi
        gc_g1_rset_updating_pause_time_percent: 5
        gc_g1_max_gc_pause_ms: 300
    resources:
      requests:
        memory: "59Gi"
        cpu: "7500m"
      limits:
        memory: "60Gi"
    datacenters:
      - metadata:
          name: dc1
        size: 3
        racks:
        - name: r1
          nodeAffinityLabels:
            topology.kubernetes.io/zone: us-west-2a
        - name: r2
          nodeAffinityLabels:
            topology.kubernetes.io/zone: us-west-2b
        - name: r3
          nodeAffinityLabels:
            topology.kubernetes.io/zone: us-west-2c
    tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "cassandra"
      effect: "NoSchedule"
  stargate:
    size: 3
    heapSize: 1024Mi
    resources:
      requests:
        cpu: 3000m
      limits:
        cpu: 3000m
    telemetry:
      prometheus:
        enabled: true
  reaper:
    keyspace: reaper_db
    telemetry:
      prometheus:
        enabled: true
